spring.application.name=YouRoster
spring.config.import=file:env.properties
#SERVER CONFIG
server.port=${PORT}
#DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
#HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${JWT_SECRET}
#CLOUDINARY
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.username=${CLOUDINARY_USERNAME}
cloudinary.secret=${CLOUDINARY_SECRET}
#PASSWORD ADMIN
password.admin=${PASSWORD_ADMIN}
email.admin=${EMAIL_ADMIN}
#EMAIL SENDER
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APIKEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.from=${EMAIL_FROM}
#LINK LOGIN NELL'EMAIL
login.url=${EMAIL_BTN_LOGIN}